package:
  name: conda-build
  version: {{ GIT_DESCRIBE_TAG }}.{{ GIT_BUILD_STR }}

source:
  git_url: ../

build:
  entry_points:
    - conda-build = conda_build.cli.main_build:main
    - conda-convert = conda_build.cli.main_convert:main
    - conda-debug = conda_build.cli.main_debug:main
    - conda-develop = conda_build.cli.main_develop:main
    - conda-index = conda_build.cli.main_index:main
    - conda-inspect = conda_build.cli.main_inspect:main
    - conda-metapackage = conda_build.cli.main_metapackage:main
    - conda-render = conda_build.cli.main_render:main
    - conda-skeleton = conda_build.cli.main_skeleton:main

requirements:
  build:
    - git
  host:
    - python
    - setuptools
    - hatchling >=1.12.2
    - hatch-vcs >=0.2.0
  run:
    - beautifulsoup4
    - chardet
    - conda >=4.13
    - conda-index
    - filelock
    - jinja2
    - packaging
    - patchelf                     # [linux]
    - patch >=2.6                  # [not win]
    - m2-patch >=2.6               # [win]
    - pkginfo
    - psutil
    - py-lief                      # [not win]
    - python
    - pyyaml
    - requests
    - six
    - glob2 >=0.6
    - pytz
    - tomli                        # [py<311]
    - tqdm
    - conda-package-handling >=1.3
    - python-libarchive-c
  run_constrained:
    - conda-verify  >=3.0.2

test:
  files:
    - test_bdist_conda_setup.py
  requires:
    - pytest
    - pytest-cov
    - pytest-mock
    # Optional: you can use pytest-xdist to run the tests in parallel
    # - pytest-env  # [win]
    # - pytest-xdist
    # - conda-verify  >=3.0.3   # todo once it is released
  commands:
    - type -P conda-build  # [unix]
    - where conda-build  # [win]
    - conda build -h
    - type -P conda-convert  # [unix]
    - where conda-convert  # [win]
    - conda convert -h
    - type -P conda-develop  # [unix]
    - where conda-develop  # [win]
    - conda develop -h
    - type -P conda-index  # [unix]
    - where conda-index  # [win]
    - conda index -h
    - type -P conda-inspect  # [unix]
    - where conda-inspect  # [win]
    - conda inspect -h
    - conda inspect linkages -h \| grep "--name ENVIRONMENT"  # [unix]
    - conda inspect objects -h \| grep "--name ENVIRONMENT"   # [osx]
    - type -P conda-metapackage  # [unix]
    - where conda-metapackage  # [win]
    - conda metapackage -h
    - type -P conda-render  # [unix]
    - where conda-render  # [win]
    - conda render -h
    - type -P conda-skeleton  # [unix]
    - where conda-skeleton  # [win]
    - conda skeleton -h
    - where conda-debug  # [win]
    - conda debug -h
    # test that conda sees entry points appropriately in help
    - conda --help

    # Check for bdist_conda
    - python test_bdist_conda_setup.py bdist_conda --help
  imports:
    - conda_build
  source_files:
    - tests

about:
  home: https://github.com/conda/conda-build
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Canary release of conda-build
