version: 2
updates:
  - package-ecosystem: pip
    directory: /docs/
    schedule:
      interval: weekly
    allow:
      # Allow only production updates for Sphinx
      - dependency-name: sphinx
        dependency-type: production
  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: weekly
