# edit this in https://github.com/conda/infrastructure

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: weekly
    groups:
      workflows:
        patterns:
          - '*'
    cooldown:
      default-days: 7
  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: monthly
    groups:
      pre-commit:
        patterns:
          - '*'
  - package-ecosystem: pip
    directory: /docs/
    schedule:
      interval: monthly
    allow:
      # Allow only production updates for Sphinx
      - dependency-name: sphinx
        dependency-type: production
    groups:
      docs:
        patterns:
          - '*'
