## The package attribure specifies a binstar package namespace to build the package to.
## This can be specified here or on the command line
package: conda-build

## You can also specify the account to upload to,
## you must be an admin of that account, this
## defaults to your user account
# user: USERNAME

#===============================================================================
# Build Matrix Options
# Thes options may be a single item, a list or empty
# The resulting number of builds is [platform * engine * env]
#===============================================================================

## The platforms to build on.
## platform defaults to linux-64
platform:
  - win-64
  - win-32
## The engine are the inital conda packages you want to run with
engine:
  - python=2
  - python=3
## The env param is an environment variable list
# env:
#  - MY_ENV=A CC=gcc
#  - MY_ENV=B

#===============================================================================
# Script options
# These options may be broken out into the before_script, script and after_script
# or not, that is up to you
#===============================================================================

## Run before the script
# before_script:
#   - echo "before_script!"
## Put your main computations here!

install:
  # Use the provided conda and Python to run the install script. The order of these commands matters.
  - conda install requests
  - set "CONDA_DEFAULT_ENV="
  - python tests\install_miniconda.py

test:
  - cd tests\test-recipes\metadata
  # This will be effectively a no-op for recipes without bld.bat
  - for /D %%f in (*) do (C:\Users\binstar\conda-build-miniconda\Scripts\conda-build.exe --no-binstar-upload %%~nf)

# script:
#   - echo "This is my binstar build!"

## This will run after the script regardless of the result of script
## BINSTAR_BUILD_RESULT=[succcess|failure]
# after_script:
#   - echo "The build was a $BINSTAR_BUILD_RESULT" | tee artifact1.txt
## This will be run only after a successfull build
# after_success:
#   - echo "after_success!"
## This will be run only after a build failure
# after_failure:
#   - echo "after_failure!"

#===============================================================================
# Build Results
# Build results are split into two categories: artifacts and targets
# You may omit either key and stiff have a successfull build
# They may be a string, list and contain any bash glob
#===============================================================================

## Build Targets: Upload these files to your binstar package
## build targets may be a list of files (globs allows) to upload
## The special build targets 'conda' and 'pypi' may be used to
## upload conda builds
## e.g. conda is an alias for /opt/anaconda/conda-bld/<os-arch>/*.tar.bz2
# build_targets:
#   - conda
