version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: '3.11'

python:
  install:
    - requirements: docs/requirements.txt

# Build PDF, ePub and zipped HTML
formats:
  - epub
  - pdf
  - htmlzip
