package:
  name: conda-build
  version: {{ environ.get('GIT_DESCRIBE_TAG','') }}.post{{ environ.get('GIT_DESCRIBE_NUMBER','') }}

source:
  git_url: ../

build:
{% if 'CONDA_RELEASE' in environ %}
  number: {{ environ.get('CONDA_BUILD_NUMBER', 0) }}
{% else %}
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}
{% endif %}

requirements:
  build:
    - python
    - conda
  run:
    - python
    - conda
    - jinja2
    - patchelf      [linux]

test:
  commands:
    - conda-build -h
  imports:
    - conda_build

about:
  home: https://github.com/conda/conda-build
  license: BSD
