package:
  name: conda-build-test-entry-points
  version: 1.0

source:
  git_url: ../../../

build:
  entry_points:
    - test-script-manual = conda_build_test.manual_entry:main

requirements:
  build:
    - python
  run:
    - python
