package:
  name: noarch
  version: 0.7.1

source:
  fn: bokeh-0.7.1.tar.gz
  url: https://pypi.python.org/packages/source/b/bokeh/bokeh-0.7.1.tar.gz
  md5: 426f2b0850018fab1407f2e7ed129544

build:
  entry_points:
    - bokeh-server = bokeh.server:run
    - websocket_worker.py = bokeh.server.websocket:make_app
  noarch: True

requirements:
  build:
    - python
  run:
    - python
    - numpy
    - pandas
    - flask
    - jinja2
    - markupsafe
    - werkzeug
    - greenlet
    - dateutil
    - pytz
    - requests
    - six
    - pygments
    - pyyaml
    - pyzmq
    - tornado

test:
  requires:
    - nose
  commands:
    - bokeh-server -h
  imports:
    - bokeh

about:
  home: https://github.com/ContinuumIO/Bokeh
  license: New BSD
