# Copyright (C) 2014 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "3.24.1.dev49"
__version_tuple__ = version_tuple = (3, 24, 1, "dev49")
