try:
    from pathlib2 import PurePath
except:
    from pathlib import PurePath

DEFAULT_MAC_WHITELIST_BAKED = (PurePath('/usr/lib/libSystem.B.dylib'),  # noqa
                               PurePath('/usr/lib/libobjc.A.dylib'),  # noqa
                               PurePath('/usr/lib/libcrypto.0.9.8.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libPSRIP.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libCFilter.A.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libCGKSeparation.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libRIP.A.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libPDFRIP.A.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libCGKSeparation.A.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libCMSBuiltin.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libCGXCoreImage.A.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libPDFRIP.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libCGXType.A.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libCMSBuiltin.A.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libPSRIP.A.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libCFilter.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libRIP.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libCGFreetype.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libJBIG2.A.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libCGXType.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libFontStreams.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libCGXCoreImage.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libCGFreetype.A.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libCMaps.A.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libCGCMS.A.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libCMaps.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libCGCMS.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libFontStreams.A.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libJBIG2.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Support/libmdworker.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/WebKit.framework/WebKitPluginHost.app/Contents/MacOS/WebKitPluginHostShim.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/AVFoundation.framework/Versions/A/Resources/libAVFAudio.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJPEG.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libGIF.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libRadiance.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libOpenEXR.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJP2.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreVMClient.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLVMPlugin.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGFXShared.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLImage.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libLLVMContainer.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLProgrammability.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCVMSPluginSupport.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/Legacy/libLLVMContainer.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/Legacy/libCoreVMClient.mono.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontWorkerAccess.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libATSServer.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libTrueTypeScaler.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libType1Scaler.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/ATSHI.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontParser.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistryServer.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontValidation.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistryUI.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSync.framework/Versions/A/Resources/ColorSyncDeprecated.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/Resources/libCGInterfaces.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvMisc.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib'),  # noqa
                               PurePath('/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib'))  # noqa
