package:
  name: conda-build
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ../

build:
  number: 0
  entry_points:
    - conda-build = conda_build.cli.main_build:main
    - conda-convert = conda_build.cli.main_convert:main
    - conda-develop = conda_build.cli.main_develop:main
    - conda-index = conda_build.cli.main_index:main
    - conda-inspect = conda_build.cli.main_inspect:main
    - conda-metapackage = conda_build.cli.main_metapackage:main
    - conda-render = conda_build.cli.main_render:main
    - conda-sign = conda_build.cli.main_sign:main
    - conda-skeleton = conda_build.cli.main_skeleton:main

requirements:
  build:
    - python
  run:
    - beautifulsoup4
    - chardet
    - conda  >=4.1
    - contextlib2   # [py<34]
    - conda-verify
    - enum34        # [py<34]
    - filelock
    - futures       # [py<3]
    - jinja2
    - patchelf      # [linux]
    - pkginfo
    - pycrypto
    - python
    - pyyaml

test:
  requires:
    - pytest
    - pytest-cov
    # Optional: you can use pytest-xdist to run the tests in parallel
    # - pytest-env  # [win]
    # - pytest-xdist
    - mock
  commands:
    - which conda-build  # [unix]
    - where conda-build  # [win]
    - conda build -h
    - which conda-convert  # [unix]
    - where conda-convert  # [win]
    - conda convert -h
    - which conda-develop  # [unix]
    - where conda-develop  # [win]
    - conda develop -h
    - which conda-index  # [unix]
    - where conda-index  # [win]
    - conda index -h
    - which conda-inspect  # [unix]
    - where conda-inspect  # [win]
    - conda inspect -h
    - conda inspect linkages -h \| grep "--name ENVIRONMENT"  # [unix]
    - conda inspect objects -h \| grep "--name ENVIRONMENT"   # [osx]
    - which conda-metapackage  # [unix]
    - where conda-metapackage  # [win]
    - conda metapackage -h
    - which conda-render  # [unix]
    - where conda-render  # [win]
    - conda render -h
    - which conda-sign  # [unix]
    - where conda-sign  # [win]
    - conda sign -h
    - which conda-skeleton  # [unix]
    - where conda-skeleton  # [win]
    - conda skeleton -h
    # test that conda sees entry points appropriately in help
    - conda --help
  imports:
    - conda_build
  source_files:
    - tests

outputs:
  - type: wheel
  - name: {{ PKG_NAME }}

about:
  home: https://github.com/conda/conda-build
  license: BSD 3-clause
