package:
  name: conda-build
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/conda/conda-build

build:
  number: 0
  {% if GIT_DESCRIBE_NUMBER|int > 0 %}
  string: py{{ PY_VER }}_git_{{ GIT_BUILD_STR }}
  {% endif %}

requirements:
  build:
    - python
  run:
    - python
    - psutil
    - conda  >=4.1
    - jinja2
    - patchelf      [linux]

test:
  requires:
    - pytest
    - pytest-cov
    - mock
  commands:
    - conda-build -h
  imports:
    - conda_build

about:
  home: https://github.com/conda/conda-build
  license: BSD
