name: Sync Labels

on:
  workflow_dispatch:
    inputs:
      dryrun:
        description: "dryrun: Preview changes to labels without editing them (true|false)"
        required: true
        default: "true"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/label-sync@v2.1.0
        with:
          config-file: |
            https://raw.githubusercontent.com/conda/infra/main/.github/labels.yml
            .github/labels.yml
          delete-other-labels: true
          dry-run: ${{ github.event.inputs.dryrun }}
