name: Sync Labels

on:
  workflow_dispatch:
    inputs:
      dryrun:
        description: "Preview changes to labels without editing them"
        required: true
        default: "true"

jobs:
  global-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/label-sync@v2
        with:
          config-file: https://raw.githubusercontent.com/conda/infra/main/.github/labels.yml
          delete-other-labels: true
          dry-run: ${{ github.event.inputs.dryrun }}

  local-labels:
    runs-on: ubuntu-latest
    steps:
      - id: has_local
        uses: andstor/file-existence-action@v1.0.1
        with:
          files: .github/labels.yml
      - uses: EndBug/label-sync@v2
        if: steps.has_local.outputs.files_exists == 'true'
        with:
          config-file: .github/labels.yml
          delete-other-labels: true
          dry-run: ${{ github.event.inputs.dryrun }}
