# this is the sibling workflow to tests-skip.yml, it is required to work around
# the skipped but required checks issue:
#   https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
name: Tests

on:
  # NOTE: github.event context is push payload:
  # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push
  push:
    branches:
      - main
      - feature/**
    paths-ignore:  # run if src/tests/recipe are modified
      - conda_build/**
      - tests/**
      - '*.py'
      - recipe/**
      - .github/workflows/tests.yml

  # NOTE: github.event context is pull_request payload:
  # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
  pull_request:
    paths-ignore:
      - conda_build/**
      - tests/**
      - '*.py'
      - recipe/**
      - .github/workflows/tests.yml

concurrency:
  # Concurrency group that uses the workflow name and PR number if available
  # or commit SHA as a fallback. If a new build is triggered under that
  # concurrency group while a previous build is running it will be canceled.
  # Repeated pushes to a PR will cancel all previous builds, while multiple
  # merges to main will not cancel.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  # required check
  analyze:
    name: Analyze results
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Nothing to analyze"'
